export const ACTIONS = {
  CREATE_FEEDBACK: "CREATE_FEEDBACK",
  GET_ALL_FEEDBACK: "GET_ALL_FEEDBACK",
  GET_FEEDBACK_BY_ID: "GET_FEEDBACK_BY_ID",
  API_CALL_SUCCESS: "API_CALL_SUCCESS",
  API_CALL_ERROR: "API_CALL_ERROR",
};